import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import emptySectionPicture from "../../public/empty.png";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Carnet Potager</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/LogoM.svg" />
      </Head>
      
      <div className="p-[3rem] h-full relative container flex flex-col justify-around items-center">
        {/* <Image className="absolute w-[65%] sm:max-w-[450px]" alt="empty" src={emptySection1}/>
        <Image className="absolute mt-8 ml-[40%] w-[65%] sm:max-w-[450px]" alt="empty" src={emptySection2}/>
        <Image className="absolute mr-[25%] w-[65%] sm:max-w-[450px]" alt="empty" src={emptySection3}/> */}
        <Image className="object-cover w-[65%] sm:max-w-[450px]" alt="empty" src={emptySectionPicture}/>
          <h1 className="text-xl font-bold text-dark leading-10 sm:text-[4rem]">
            Votre <span className="text-primary">Potager</span> est vide pour le 
            moment, commencez à semer 
            dès maintenant !
          </h1>
              <p className="text-lg font-medium text-dark__bg">
              Bienvenue sur le tableau de bord, à vous de l’organiser comme bon vous semble. Vous pouvez choisir de commencer par ajouter des tâches à votre Bloc-notes, générer votre calendrier du potager personnalisé via l’assistant ou bien encore ajouter vos plantes potagères favorites.
              </p>
              <button className="cursor-no-drop active:scale-90 sm:w-[15%] inline-block px-4 py-3
              text-sm font-semibold text-center
              text-primary__variant transition
              duration-200 ease-in-out bg-primary
              rounded-md
              hover:bg-primary__darker">
              Commencer</button>
      </div>
     
    </>
  );
};

export default Home;
